// Generated by CoffeeScript 1.8.0
(function() {
  this.Ticker = (function() {
    function Ticker(socket_url) {
      if (socket_url == null) {
        socket_url = "wss://ws.mexbt.com/v1/ticker";
      }
      this.socket = new WebSocket(socket_url);
      this.socket.onopen = function(event) {
        return this.send(JSON.stringify({
          messageType: 'logon'
        }));
      };
      this.socket.onmessage = function(event) {
        var data;
        data = JSON.parse(event.data);
        if (data.prodPair === "BTCMXN") {
          return $.event.trigger({
            type: 'TICKER_UPDATE',
            message: 'Ticker update',
            price: data.last
          });
        }
      };
    }

    Ticker.prototype.listen = function(call) {
      return $(document).on("TICKER_UPDATE", call);
    };

    Ticker.prototype.close = function() {
      return this.socket.close();
    };

    return Ticker;

  })();

}).call(this);
